services:
  - type: web
    name: visual-matcher-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: USE_LOCAL_CLIP
        value: true
      - key: LOCAL_CLIP_URL
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: HUGGINGFACE_MODEL
        value: google/vit-base-patch16-384
      - key: FRONTEND_URL
        sync: false
