services:
  - type: web
    name: visual-matcher-clip
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      pip install git+https://github.com/openai/CLIP.git &&
      python -c "import clip; import torch; clip.load('ViT-B/32', device='cpu')"
    startCommand: uvicorn service:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
